sudo: required

language: rust
cache:
  directories:
    - /home/travis/.cargo

os:
- linux

rust:
- nightly

addons:
  apt:
    packages:
    - libssl-dev

before_script:
- if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi
- echo PATH is $PATH
- export RUST_BACKTRACE=1

script: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  cargo tarpaulin --verbose --ciserver travis-ci --coveralls "$TRAVIS_JOB_ID"
