sudo: false

language: rust
cache: cargo

os:
- linux
- osx

osx_image: xcode7.1

rust:
- nightly
- beta
- stable

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - binutils-dev
    - libiberty-dev # same

before_script:
- if [[ -e ~/.local/bin ]]; then export PATH=~/.local/bin:$PATH; fi
- echo PATH is $PATH
- export RUST_BACKTRACE=1

script: ./ci/script.sh

env:
  matrix:
    - GIMLI_JOB="test"              GIMLI_PROFILE=
    - GIMLI_JOB="test"              GIMLI_PROFILE="--release"
    - GIMLI_JOB="examples"          GIMLI_PROFILE=
    - GIMLI_JOB="examples"          GIMLI_PROFILE="--release"

matrix:
  fast_finish: true
  include:
    # Coverage should only run on Linux and stable Rust.
    - rust: stable
      os: linux
      env: GIMLI_JOB="coverage"     GIMLI_PROFILE=
    # Building docs only needs to happen on one os and only on stable.
    - rust: stable
      os: linux
      env: GIMLI_JOB="doc"          GIMLI_PROFILE=
    # Benching should only happen on nightly with --release.
    - rust: nightly
      env: GIMLI_JOB="bench"        GIMLI_PROFILE="--release"
    # The no-std/alloc build should only happen on nightly.
    - rust: nightly
      env: GIMLI_JOB="alloc"        GIMLI_PROFILE=
    - rust: nightly
      env: GIMLI_JOB="alloc"        GIMLI_PROFILE="--release"
    # Build a 32 bit target.
    - rust: stable
      sudo: required
      services: docker
      env:
        - TARGET=i686-unknown-linux-gnu
        - GIMLI_JOB=cross
        - GIMLI_PROFILE=
    # Build a big-endian target.
    - rust: stable
      sudo: required
      services: docker
      env:
        - TARGET=powerpc64-unknown-linux-gnu
        - GIMLI_JOB=cross
        - GIMLI_PROFILE=
