[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "A zero-copy DWARF debugging format parser."
documentation = "http://fitzgen.github.io/gimli/gimli/index.html"
keywords = ["DWARF", "debug", "elf"]
license = "Apache-2.0/MIT"
name = "gimli"
readme = "./README.md"
repository = "https://github.com/fitzgen/gimli"
version = "0.2.0"

[dependencies]
byteorder = "0.5.3"
leb128 = "0.2.1"

[target.'cfg(target_os="linux")'.dev-dependencies]
elf = "0.0.9"

[target.'cfg(target_os="macos")'.dev-dependencies]
mach_o = "0.1.1"

[features]
nightly = []
