[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "DWARF debugging format parser."
documentation = "http://fitzgen.github.io/gimli/gimli/index.html"
keywords = ["DWARF", "debug", "elf"]
license = "Apache-2.0/MIT"
name = "gimli"
readme = "./README.md"
repository = "https://github.com/fitzgen/gimli"
version = "0.1.0"

[dependencies]
byteorder = "0.5.3"
leb128 = "0.1.0"

[features]
nightly = []
