[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
description = "DWARF debugging format parser."
documentation = "http://fitzgen.github.io/gimli/gimli/index.html"
keywords = ["DWARF", "debug", "elf"]
license = "Apache-2.0/MIT"
name = "gimli"
readme = "./README.md"
repository = "https://github.com/fitzgen/gimli"
version = "0.1.0"

[dependencies]
leb128 = "0.1.0"
nom = "1.2.3"

[dependencies.clippy]
optional = true
version = "0.0.78"

[features]
nightly = ["clippy"]
