[package]
authors = [
  "Nick Fitzgerald <fitzgen@gmail.com>",
  "Philip Craig <philipjcraig@gmail.com>"
]
description = "A zero-copy DWARF debugging format parser."
documentation = "http://gimli-rs.github.io/gimli/gimli/index.html"
keywords = ["DWARF", "debug", "elf"]
license = "Apache-2.0/MIT"
name = "gimli"
readme = "./README.md"
repository = "https://github.com/gimli-rs/gimli"
version = "0.6.0"

[dependencies]
byteorder = "0.5.3"
leb128 = "0.2.1"

[dev-dependencies]
getopts = "0.2"
object = "0.0.2"

[features]
nightly = []
